[package]
name = "pixel_rs"
version = "0.3.3"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-cors = "0.1.0"
actix-files = "0.1.4"
actix-multipart = "0.1.3"
actix-rt = "0.2.4"
actix-web = "1.0.5"
actix-web-actors = "1.0.2"
awc = { version ="0.2.4", features = ["rust-tls"] }
bcrypt = "0.4.0"
chrono = { version = "0.4.7", features = ["serde"] }
derive_more = "0.14.1"
dotenv = "0.14.1"
env_logger = "0.6.1"
futures = "0.1.28"
hashbrown = "0.6.0"
jsonwebtoken = "6.0.1"
lazy_static = "1.3.0"
lettre = "0.9.2"
lettre_email = "0.9.2"
psn_api_rs = { git = "https://github.com/fakeshadow/psn_api_rs.git", features= [ "client" ] }
rand = "0.7.0"
redis = { git = "https://github.com/mitsuhiko/redis-rs.git"}
regex = "1.2.1"
serde_json = "1.0.40"
serde = "1.0.99"
serde_derive = "1.0.99"
tokio-postgres = { version = "0.4.0-rc.3", features = ["with-chrono-0_4"] }
uuid = "0.7.4"

l337 = { git = "https://github.com/OneSignal/L3-37" }
l337-postgres = { git = "https://github.com/OneSignal/L3-37" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
