[package]
name = "pixel_social"
version = "0.4.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies.actix-cors]
version = "0.1.0"

[dependencies.actix]
version = "0.8.3"

[dependencies.actix-files]
version = "0.1.4"

[dependencies.actix-multipart]
version = "0.1.4"

[dependencies.actix-web-actors]
version = "1.0.2"

[dependencies.actix-web]
version = "1.0.8"
default-features = false

[dependencies.async-std]
version = "0.99.9"
default-features = false

[dependencies.base64]
version = "0.10.1"

[dependencies.bcrypt]
version = "0.4.0"

[dependencies.bytes]
version = "0.4.12"
default-features = false

[dependencies.chrono]
version = "0.4.9"
default-features = false
features = [ "serde" ]

[dependencies.derive_more]
version = "0.15.0"

[dependencies.dotenv]
version = "0.14.1"

[dependencies.env_logger]
version = "0.6.1"

[dependencies.futures-preview]
version = "0.3.0-alpha.19"
default-features = false
features = [ "compat" ]

[dependencies.hashbrown]
version = "0.6.1"

[dependencies.heng_rs]
git = "https://github.com/fakeshadow/heng_rs"

[dependencies.hyper]
version = "0.13.0-alpha.4"
default-features = false

[dependencies.hyper-tls]
version = "0.4.0-alpha.4"

[dependencies.jsonwebtoken]
version = "6.0.1"

[dependencies.lazy_static]
version = "1.3.0"

[dependencies.lettre]
version = "0.9.2"

[dependencies.lettre_email]
version = "0.9.2"

[dependencies.parking_lot]
version = "0.9.0"

[dependencies.rand]
version = "0.7.2"

[dependencies.redis]
git = "https://github.com/Marwes/redis-rs"
branch = "async_await_api"
default-features = false
features = ["executor"]

[dependencies.regex]
version = "1.3.1"

[dependencies.serde]
version = "1.0.101"
default-features = false

[dependencies.serde_derive]
version = "1.0.101"

[dependencies.serde_json]
version = "1.0.41"

[dependencies.serde_urlencoded]
version = "0.6.1"

[dependencies.tang-rs]
git = "https://github.com/fakeshadow/tang_rs"
default-features = false
features = [ "actix-web" ]

[dependencies.tokio]
version = "0.2.0-alpha.6"
default-features = false
features = [ "io", "codec", "fs" ]

[dependencies.tokio-postgres]
version = "0.5.0-alpha.1"
features = [ "with-chrono-0_4" ]

[dependencies.psn_api_rs]
git = "https://github.com/fakeshadow/psn_api_rs.git"
branch = "std-future"

[dependencies.uuid]
version = "0.7.4"
default-features = false
features = [ "v4" ]

# temp dep.
[dependencies.actix-async-await]
git = "https://github.com/fakeshadow/actix-async-await"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1