[package]
name = "pixel_rs"
version = "0.3.3"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.5"
actix-rt = "0.2.4"
actix-web-actors = "1.0.2"
actix-cors = "0.1.0"
actix-files = "0.1.4"
actix-multipart = "0.1.2"
bcrypt = "0.4.0"
chrono = { version = "0.4.7", features = ["serde"] }
tokio-postgres = { version = "0.4.0-rc.3", features = ["with-chrono-0_4"] }
redis = { git = "https://github.com/mitsuhiko/redis-rs.git"}
derive_more = "0.14.1"
dotenv = "0.14.1"
env_logger = "0.6.1"
jsonwebtoken = "6.0.1"
futures = "0.1.28"
hashbrown = "0.5.0"
serde_json = "1.0.40"
serde = "1.0.97"
serde_derive = "1.0.97"
rand = "0.6.5"
uuid = "0.7.4"
regex = "1.2.0"
lazy_static = "1.3.0"
lettre = "0.9.2"
lettre_email = "0.9.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
