[package]
name = "pixel_rs"
version = "0.1.2"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
actix = { version = "0.8.0-alpha.2", features = ["http"] }
actix-rt = "0.2.2"
actix-web = "1.0.0-beta.2"
actix-files = "0.1.0-betsa.1"
actix-multipart = "0.1.0-beta.1"
bcrypt = "0.2.1"
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.4.2", features = ["postgres", "r2d2", "chrono"] }
r2d2_redis = "0.9.0"
derive_more = "0.14.0"
dotenv = "0.13.0"
env_logger = "0.6.0"
jsonwebtoken = { git = "https://github.com/Keats/jsonwebtoken.git", branch = "next" }
futures = "0.1.25"
r2d2 = "0.8.3"
serde_derive="1.0.80"
serde_json="1.0"
serde="1.0"
rand = "0.6.5"
regex = "1.1.2"
lazy_static = "1.3.0"
lettre = "0.9"
lettre_email = "0.9"

[profile.release]
opt-level = 3
codegen-units = 1
debug = false
lto = true
debug-assertions = false
