[package]
name = "pixel_rs"
version = "0.1.3"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
actix = "0.8.2"
actix-http = "0.2.0"
actix-web = "1.0.0-rc"
actix-files = "0.1.0-beta.4"
actix-multipart = "0.1.0"
actix-web-actors = "1.0.0-beta.4"
bcrypt = "0.2.1"
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.4.2", features = ["postgres", "r2d2", "chrono"] }
r2d2_redis = "0.9.0"
derive_more = "0.14.0"
dotenv = "0.14.1"
env_logger = "0.6.1"
jsonwebtoken = "6.0.1"
futures = "0.1.27"
r2d2 = "0.8.4"
serde_derive = "1.0.91"
serde_json = "1.0.39"
serde = "1.0.91"
rand = "0.6.5"
regex = "1.1.6"
lazy_static = "1.3.0"
lettre = "0.9"
lettre_email = "0.9"

[profile.release]
opt-level = 3
codegen-units = 1
debug = false
lto = true
debug-assertions = false
