[package]
name = "pixel_rs"
version = "0.3.3"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.2"
actix-rt = "0.2.2"
actix-web-actors = "1.0.0"
actix-cors = "0.1.0"
actix-files = "0.1.2"
actix-multipart = "0.1.2"
bcrypt = "0.4.0"
chrono = { version = "0.4.6", features = ["serde"] }
tokio-postgres = { git="https://github.com/sfackler/rust-postgres.git", features = ["with-chrono-0_4"] }
redis = "0.11.0-beta.1"
derive_more = "0.14.1"
dotenv = "0.14.1"
env_logger = "0.6.1"
jsonwebtoken = "6.0.1"
futures = "0.1.27"
serde_json = "1.0.39"
serde = "1.0.92"
serde_derive = "1.0.92"
rand = "0.6.5"
regex = "1.1.7"
lazy_static = "1.3.0"
lettre = "0.9.1"
lettre_email = "0.9.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
