[package]
name = "pixel_social"
version = "0.4.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-cors = "0.1.0"
actix-files = "0.1.4"
actix-multipart = "0.1.3"
actix-rt = "0.2.4"
actix-web = "1.0.6"
actix-web-actors = "1.0.2"
awc = { version ="0.2.4", features = ["rust-tls"] }
bcrypt = "0.4.0"
bytes = "0.4.12"
chrono = { version = "0.4.7", features = ["serde"] }
derive_more = "0.14.1"
dotenv = "0.14.1"
env_logger = "0.6.1"
hashbrown = "0.6.0"
jsonwebtoken = "6.0.1"
lazy_static = "1.3.0"
lettre = "0.9.2"
lettre_email = "0.9.2"
psn_api_rs = { git = "https://github.com/fakeshadow/psn_api_rs.git", features= [ "client" ] }
rand = "0.7.0"
redis = { git = "https://github.com/mitsuhiko/redis-rs.git"}
regex = "1.2.1"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
uuid = "0.7.4"

futures01 = { package = "futures", version = "0.1.28" }
futures-preview = { version = "0.3.0-alpha.18", features = ["nightly", "compat", "async-await"] }
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres", branch = "std-futures", features = ["with-chrono-0_4"] }
tokio = { version = "0.2.0-alpha.2", default-features = false, features = ["io", "codec"] }
tokio-executor = "0.2.0-alpha.2"
async-std = "0.99"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1