[package]
name = "pixel_social"
version = "0.4.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-cors = "0.1.0"
actix-files = "0.1.4"
actix-multipart = "0.1.4"
actix-web-actors = "1.0.2"
async-std = "0.99.5"
base64 = "0.10.1"
bcrypt = "0.4.0"
bytes = "0.4.12"
derive_more = "0.15.0"
dotenv = "0.14.1"
env_logger = "0.6.1"
hashbrown = "0.6.0"
jsonwebtoken = "6.0.1"
lazy_static = "1.3.0"
lettre = "0.9.2"
lettre_email = "0.9.2"
rand = "0.7.2"
regex = "1.3.1"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.40"
serde_urlencoded = "0.6.1"
uuid = "0.7.4"

[dependencies.actix-web]
version = "1.0.7"
default-features = false

[dependencies.chrono]
version = "0.4.9"
features = [ "serde" ]

[dependencies.futures-preview]
version = "0.3.0-alpha.18"
features = [ "nightly", "compat", "async-await" ]

[dependencies.hyper]
version = "0.13.0-alpha.1"

[dependencies.hyper-tls]
git = "https://github.com/hyperium/hyper-tls"

[dependencies.parking_lot]
version = "0.9.0"

[dependencies.redis]
git = "https://github.com/Marwes/redis-rs.git"
branch = "std_future"

[dependencies.tokio]
version = "0.2.0-alpha.4"
default-features = false
features = [ "io", "codec", "fs" ]

[dependencies.tokio-postgres]
git = "https://github.com/sfackler/rust-postgres"
branch = "std-futures"
features = [ "with-chrono-0_4" ]

[dependencies.psn_api_rs]
git = "https://github.com/fakeshadow/psn_api_rs.git"
branch = "std-future"
features= [ "client" ]

# temp dep.
[dependencies.actix-async-await]
git = "https://github.com/fakeshadow/actix-async-await"


[profile.release]
lto = true
opt-level = 3
codegen-units = 1