[package]
name = "pixel_rust"
version = "0.1.0"
authors = ["fakeshadow"]
edition = "2018"

[dependencies]
actix = "0.7.9"
actix-web = "0.7.8"
bcrypt = "0.2.0"
chrono = { version = "0.4.6", features = ["serde"] }
diesel = { version = "1.4.2", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.13.0"
env_logger = "0.5.13"
failure = "0.1.2"
jsonwebtoken = "5.0.1"
futures = "0.1"
r2d2 = "0.8.3"
serde_derive="1.0.79"
serde_json="1.0"
serde="1.0"

[profile.release]
opt-level = 3
debug = false