name: pixel_flutter_web
description: An app built using Flutter for web

dependencies:
  flutter_web: any
  flutter_web_ui: any
  rxdart: ^0.22.0
  http: ^0.12.0+2
  equatable: ^0.2.3
  flutter_bloc:
    path: ./lib/flutter_bloc

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
